apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: yillkid/docker-fastapi:e26846379aef2d109f62cabde26a67ce957c9f81
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
