apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: yillkid/docker-fastapi:5c41dec0e75a53553333e1e3f8e8795552386137
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
