apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: yillkid/docker-fastapi:32cff08098bcb5abe1d6e2f56e3deef27a689f8a
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
